//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Payment
    {
        public int ID { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Payment_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
