//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Order_Material = new HashSet<Order_Material>();
        }
    
        public int Material_ID { get; set; }
        public string Material_Description { get; set; }
        public double Material_Price { get; set; }
    
        public virtual ICollection<Order_Material> Order_Material { get; set; }
    }
}
