//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Order_Material = new HashSet<Order_Material>();
            this.Order_Size = new HashSet<Order_Size>();
        }
    
        public int Order_ID { get; set; }
        public string Order_Status { get; set; }
        public System.DateTime Order_Date { get; set; }
        public Nullable<int> Staff_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Order_Material> Order_Material { get; set; }
        public virtual ICollection<Order_Size> Order_Size { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
