//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Size
    {
        public int ID { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Size_Id { get; set; }
        public int quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Size Size { get; set; }
    }
}
