//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.Customer_Payment = new HashSet<Customer_Payment>();
        }
    
        public int Payment_ID { get; set; }
        public string Payment_Method { get; set; }
        public string Payment_Status { get; set; }
    
        public virtual ICollection<Customer_Payment> Customer_Payment { get; set; }
    }
}
