//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.Order_Size = new HashSet<Order_Size>();
        }
    
        public int Size_ID { get; set; }
        public string Size_Description { get; set; }
        public double Size_Price { get; set; }
    
        public virtual ICollection<Order_Size> Order_Size { get; set; }
    }
}
