//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyImage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Staff_ID { get; set; }
        public string Staff_FirstName { get; set; }
        public string Staff_LastName { get; set; }
        public string Staff_Phone { get; set; }
        public string Staff_Email { get; set; }
        public string Staff_Roles { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
